sources:
  - name: aminalsv2
    handler:
      graphql:
        #endpoint: https://api.studio.thegraph.com/query/57078/aminals/v0.0.35
        endpoint: https://api.studio.thegraph.com/query/68539/aminals/version/latest
documents:
  - ./src/**/*.graphql
