//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Aminals
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const aminalsAbi = [
  {
    type: 'constructor',
    inputs: [
      { name: '_visualsAuction', internalType: 'address', type: 'address' },
      { name: '_aminalProposals', internalType: 'address', type: 'address' },
    ],
    stateMutability: 'nonpayable',
  },
  { type: 'error', inputs: [], name: 'AminalDoesNotExist' },
  { type: 'error', inputs: [], name: 'NotEnoughEther' },
  { type: 'error', inputs: [], name: 'NotSpawnable' },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'aminalId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true,
      },
      {
        name: 'proposalId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'skillName',
        internalType: 'string',
        type: 'string',
        indexed: false,
      },
      {
        name: 'skillAddress',
        internalType: 'address',
        type: 'address',
        indexed: false,
      },
      {
        name: 'sender',
        internalType: 'address',
        type: 'address',
        indexed: false,
      },
    ],
    name: 'AddSkillProposal',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'aminalOne',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true,
      },
      {
        name: 'aminalTwo',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true,
      },
      {
        name: 'auctionId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'BreedAminal',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'aminalId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true,
      },
      {
        name: 'sender',
        internalType: 'address',
        type: 'address',
        indexed: false,
      },
      {
        name: 'amount',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'love',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'totalLove',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'energy',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'FeedAminal',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'version', internalType: 'uint8', type: 'uint8', indexed: false },
    ],
    name: 'Initialized',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'previousOwner',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'newOwner',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
    ],
    name: 'OwnershipTransferred',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'aminalId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true,
      },
      {
        name: 'proposalId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'skillAddress',
        internalType: 'address',
        type: 'address',
        indexed: false,
      },
      {
        name: 'sender',
        internalType: 'address',
        type: 'address',
        indexed: false,
      },
    ],
    name: 'RemoveSkillProposal',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'aminalId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true,
      },
      {
        name: 'skillAddress',
        internalType: 'address',
        type: 'address',
        indexed: false,
      },
    ],
    name: 'SkillAdded',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'aminalId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true,
      },
      {
        name: 'skillAddress',
        internalType: 'address',
        type: 'address',
        indexed: false,
      },
    ],
    name: 'SkillRemoved',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'aminalId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true,
      },
      {
        name: 'sender',
        internalType: 'address',
        type: 'address',
        indexed: false,
      },
      {
        name: 'proposalId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      { name: 'yesNo', internalType: 'bool', type: 'bool', indexed: false },
    ],
    name: 'SkillVote',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'aminalId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true,
      },
      { name: 'mom', internalType: 'uint256', type: 'uint256', indexed: true },
      { name: 'dad', internalType: 'uint256', type: 'uint256', indexed: true },
      {
        name: 'backId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'armId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'tailId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'earsId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'bodyId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'faceId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'mouthId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'miscId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'SpawnAminal',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'aminalId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true,
      },
      {
        name: 'amount',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'energy',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'love',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'sender',
        internalType: 'address',
        type: 'address',
        indexed: false,
      },
    ],
    name: 'Squeak',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'visualId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'catEnum',
        internalType: 'enum AminalsDescriptor.VisualsCat',
        type: 'uint8',
        indexed: false,
      },
      { name: 'svg', internalType: 'string', type: 'string', indexed: false },
      {
        name: 'creator',
        internalType: 'address',
        type: 'address',
        indexed: false,
      },
    ],
    name: 'TraitAdded',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'from', internalType: 'address', type: 'address', indexed: true },
      { name: 'to', internalType: 'address', type: 'address', indexed: true },
      { name: 'id', internalType: 'uint256', type: 'uint256', indexed: true },
    ],
    name: 'Transfer',
  },
  {
    type: 'function',
    inputs: [
      { name: 'aminalID', internalType: 'uint256', type: 'uint256' },
      { name: 'proposalId', internalType: 'uint256', type: 'uint256' },
      { name: 'yesNo', internalType: 'bool', type: 'bool' },
    ],
    name: '_vote',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: 'arm', internalType: 'string', type: 'string' }],
    name: 'addArm',
    outputs: [{ name: 'id', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: 'background', internalType: 'string', type: 'string' }],
    name: 'addBackground',
    outputs: [{ name: 'id', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: 'body', internalType: 'string', type: 'string' }],
    name: 'addBody',
    outputs: [{ name: 'id', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: 'ear', internalType: 'string', type: 'string' }],
    name: 'addEar',
    outputs: [{ name: 'id', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: 'face', internalType: 'string', type: 'string' }],
    name: 'addFace',
    outputs: [{ name: 'id', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: 'misc', internalType: 'string', type: 'string' }],
    name: 'addMisc',
    outputs: [{ name: 'id', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: 'mouth', internalType: 'string', type: 'string' }],
    name: 'addMouth',
    outputs: [{ name: 'id', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: 'tail', internalType: 'string', type: 'string' }],
    name: 'addTail',
    outputs: [{ name: 'id', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: 'aminalId', internalType: 'uint256', type: 'uint256' }],
    name: 'aminals',
    outputs: [
      { name: 'momId', internalType: 'uint256', type: 'uint256' },
      { name: 'dadId', internalType: 'uint256', type: 'uint256' },
      { name: 'totalLove', internalType: 'uint256', type: 'uint256' },
      { name: 'energy', internalType: 'uint256', type: 'uint256' },
      { name: 'breeding', internalType: 'bool', type: 'bool' },
      { name: 'exists', internalType: 'bool', type: 'bool' },
      {
        name: 'visuals',
        internalType: 'struct IAminalStructs.Visuals',
        type: 'tuple',
        components: [
          { name: 'backId', internalType: 'uint256', type: 'uint256' },
          { name: 'armId', internalType: 'uint256', type: 'uint256' },
          { name: 'tailId', internalType: 'uint256', type: 'uint256' },
          { name: 'earsId', internalType: 'uint256', type: 'uint256' },
          { name: 'bodyId', internalType: 'uint256', type: 'uint256' },
          { name: 'faceId', internalType: 'uint256', type: 'uint256' },
          { name: 'mouthId', internalType: 'uint256', type: 'uint256' },
          { name: 'miscId', internalType: 'uint256', type: 'uint256' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'spender', internalType: 'address', type: 'address' },
      { name: 'id', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'approve',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    name: 'arms',
    outputs: [
      { name: 'svg', internalType: 'string', type: 'string' },
      { name: 'creator', internalType: 'address', type: 'address' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    name: 'backgrounds',
    outputs: [
      { name: 'svg', internalType: 'string', type: 'string' },
      { name: 'creator', internalType: 'address', type: 'address' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'owner', internalType: 'address', type: 'address' }],
    name: 'balanceOf',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    name: 'bodies',
    outputs: [
      { name: 'svg', internalType: 'string', type: 'string' },
      { name: 'creator', internalType: 'address', type: 'address' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'aminalIdOne', internalType: 'uint256', type: 'uint256' },
      { name: 'aminalIdTwo', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'breedWith',
    outputs: [{ name: 'ret', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'aminalId', internalType: 'uint256', type: 'uint256' },
      { name: 'skillAddress', internalType: 'address', type: 'address' },
      { name: 'data', internalType: 'bytes', type: 'bytes' },
    ],
    name: 'callSkill',
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'sender', internalType: 'address', type: 'address' },
      { name: 'aminalId', internalType: 'uint256', type: 'uint256' },
      { name: 'skillAddress', internalType: 'address', type: 'address' },
      { name: 'data', internalType: 'bytes', type: 'bytes' },
    ],
    name: 'callSkillInternal',
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    inputs: [
      {
        name: 'params',
        internalType: 'struct NFTDescriptor.TokenURIParams',
        type: 'tuple',
        components: [
          { name: 'name', internalType: 'string', type: 'string' },
          { name: 'description', internalType: 'string', type: 'string' },
          { name: 'image', internalType: 'string', type: 'string' },
          { name: 'attributes', internalType: 'string', type: 'string' },
        ],
      },
    ],
    name: 'constructTokenURI',
    outputs: [{ name: '', internalType: 'string', type: 'string' }],
    stateMutability: 'pure',
  },
  {
    type: 'function',
    inputs: [{ name: 'tokenId', internalType: 'uint256', type: 'uint256' }],
    name: 'dataURI',
    outputs: [{ name: '', internalType: 'string', type: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'aminalIdOne', internalType: 'uint256', type: 'uint256' },
      { name: 'aminalIdTwo', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'disableBreedable',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    name: 'ears',
    outputs: [
      { name: 'svg', internalType: 'string', type: 'string' },
      { name: 'creator', internalType: 'address', type: 'address' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    name: 'faces',
    outputs: [
      { name: 'svg', internalType: 'string', type: 'string' },
      { name: 'creator', internalType: 'address', type: 'address' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'aminalId', internalType: 'uint256', type: 'uint256' }],
    name: 'feed',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    inputs: [{ name: 'tokenId', internalType: 'uint256', type: 'uint256' }],
    name: 'generateAttributesList',
    outputs: [{ name: '', internalType: 'string', type: 'string' }],
    stateMutability: 'pure',
  },
  {
    type: 'function',
    inputs: [
      { name: '_name', internalType: 'string', type: 'string' },
      { name: '_description', internalType: 'string', type: 'string' },
      { name: '_image', internalType: 'string', type: 'string' },
      { name: '_attributes', internalType: 'string', type: 'string' },
    ],
    name: 'genericDataURI',
    outputs: [{ name: '', internalType: 'string', type: 'string' }],
    stateMutability: 'pure',
  },
  {
    type: 'function',
    inputs: [
      { name: 'aminalID', internalType: 'uint256', type: 'uint256' },
      { name: 'user', internalType: 'address', type: 'address' },
    ],
    name: 'getAminalLoveByIdByUser',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'aminalID', internalType: 'uint256', type: 'uint256' }],
    name: 'getAminalLoveTotal',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'aminalID', internalType: 'uint256', type: 'uint256' }],
    name: 'getAminalVisualsByID',
    outputs: [
      {
        name: '',
        internalType: 'struct IAminalStructs.Visuals',
        type: 'tuple',
        components: [
          { name: 'backId', internalType: 'uint256', type: 'uint256' },
          { name: 'armId', internalType: 'uint256', type: 'uint256' },
          { name: 'tailId', internalType: 'uint256', type: 'uint256' },
          { name: 'earsId', internalType: 'uint256', type: 'uint256' },
          { name: 'bodyId', internalType: 'uint256', type: 'uint256' },
          { name: 'faceId', internalType: 'uint256', type: 'uint256' },
          { name: 'mouthId', internalType: 'uint256', type: 'uint256' },
          { name: 'miscId', internalType: 'uint256', type: 'uint256' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'aminalID', internalType: 'uint256', type: 'uint256' }],
    name: 'getEnergy',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'category', internalType: 'uint256', type: 'uint256' },
      { name: 'id', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'getVisuals',
    outputs: [{ name: '', internalType: 'string', type: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'lastAminalId',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'aminalId', internalType: 'uint256', type: 'uint256' },
      { name: 'sender', internalType: 'address', type: 'address' },
    ],
    name: 'loveDrivenPrice',
    outputs: [{ name: '', internalType: 'uint128', type: 'uint128' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    name: 'miscs',
    outputs: [
      { name: 'svg', internalType: 'string', type: 'string' },
      { name: 'creator', internalType: 'address', type: 'address' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    name: 'mouths',
    outputs: [
      { name: 'svg', internalType: 'string', type: 'string' },
      { name: 'creator', internalType: 'address', type: 'address' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'name',
    outputs: [{ name: '', internalType: 'string', type: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'owner',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'id', internalType: 'uint256', type: 'uint256' }],
    name: 'ownerOf',
    outputs: [{ name: 'owner', internalType: 'address', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'proposals',
    outputs: [
      { name: '', internalType: 'contract AminalProposals', type: 'address' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'aminalID', internalType: 'uint256', type: 'uint256' },
      { name: 'skillName', internalType: 'string', type: 'string' },
      { name: 'skillAddress', internalType: 'address', type: 'address' },
    ],
    name: 'proposeAddSkill',
    outputs: [{ name: 'proposalId', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'aminalID', internalType: 'uint256', type: 'uint256' },
      { name: 'description', internalType: 'string', type: 'string' },
      { name: 'skillAddress', internalType: 'address', type: 'address' },
    ],
    name: 'proposeRemoveSkill',
    outputs: [{ name: 'proposalId', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'faddress', internalType: 'address', type: 'address' },
      { name: 'aminalID', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'removeSkill',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'renounceOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'from', internalType: 'address', type: 'address' },
      { name: 'to', internalType: 'address', type: 'address' },
      { name: 'id', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'safeTransferFrom',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'from', internalType: 'address', type: 'address' },
      { name: 'to', internalType: 'address', type: 'address' },
      { name: 'id', internalType: 'uint256', type: 'uint256' },
      { name: 'data', internalType: 'bytes', type: 'bytes' },
    ],
    name: 'safeTransferFrom',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'operator', internalType: 'address', type: 'address' },
      { name: 'approved', internalType: 'bool', type: 'bool' },
    ],
    name: 'setApprovalForAll',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'aminalID', internalType: 'uint256', type: 'uint256' },
      { name: 'breeding', internalType: 'bool', type: 'bool' },
    ],
    name: 'setBreeding',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: '', internalType: 'address', type: 'address' }],
    name: 'skills',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'aminalOne', internalType: 'uint256', type: 'uint256' },
      { name: 'aminalTwo', internalType: 'uint256', type: 'uint256' },
      { name: 'backId', internalType: 'uint256', type: 'uint256' },
      { name: 'armId', internalType: 'uint256', type: 'uint256' },
      { name: 'tailId', internalType: 'uint256', type: 'uint256' },
      { name: 'earsId', internalType: 'uint256', type: 'uint256' },
      { name: 'bodyId', internalType: 'uint256', type: 'uint256' },
      { name: 'faceId', internalType: 'uint256', type: 'uint256' },
      { name: 'mouthId', internalType: 'uint256', type: 'uint256' },
      { name: 'miscId', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'spawnAminal',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      {
        name: '_visuals',
        internalType: 'struct IAminalStructs.Visuals[]',
        type: 'tuple[]',
        components: [
          { name: 'backId', internalType: 'uint256', type: 'uint256' },
          { name: 'armId', internalType: 'uint256', type: 'uint256' },
          { name: 'tailId', internalType: 'uint256', type: 'uint256' },
          { name: 'earsId', internalType: 'uint256', type: 'uint256' },
          { name: 'bodyId', internalType: 'uint256', type: 'uint256' },
          { name: 'faceId', internalType: 'uint256', type: 'uint256' },
          { name: 'mouthId', internalType: 'uint256', type: 'uint256' },
          { name: 'miscId', internalType: 'uint256', type: 'uint256' },
        ],
      },
    ],
    name: 'spawnInitialAminals',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'aminalId', internalType: 'uint256', type: 'uint256' },
      { name: 'amount', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'squeak',
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    inputs: [{ name: 'interfaceId', internalType: 'bytes4', type: 'bytes4' }],
    name: 'supportsInterface',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'symbol',
    outputs: [{ name: '', internalType: 'string', type: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    name: 'tails',
    outputs: [
      { name: 'svg', internalType: 'string', type: 'string' },
      { name: 'creator', internalType: 'address', type: 'address' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'aminalID', internalType: 'uint256', type: 'uint256' }],
    name: 'tokenURI',
    outputs: [{ name: '', internalType: 'string', type: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'from', internalType: 'address', type: 'address' },
      { name: 'to', internalType: 'address', type: 'address' },
      { name: 'id', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'transferFrom',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: 'newOwner', internalType: 'address', type: 'address' }],
    name: 'transferOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'visualsAuction',
    outputs: [
      { name: '', internalType: 'contract VisualsAuction', type: 'address' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'aminalID', internalType: 'uint256', type: 'uint256' },
      { name: 'proposalID', internalType: 'uint256', type: 'uint256' },
      { name: 'yesNo', internalType: 'bool', type: 'bool' },
    ],
    name: 'voteSkill',
    outputs: [],
    stateMutability: 'nonpayable',
  },
] as const

export const aminalsAddress =
  '0x18FB0D34Dd411Ac314DcB8c9E0331B76bEbF002A' as const

export const aminalsConfig = {
  address: aminalsAddress,
  abi: aminalsAbi,
} as const

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// VisualsAuction
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const visualsAuctionAbi = [
  {
    type: 'constructor',
    inputs: [
      {
        name: '_generatornessSourceContract',
        internalType: 'address',
        type: 'address',
      },
      {
        name: '_generatornessSourceBalance',
        internalType: 'address',
        type: 'address',
      },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'auctionId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true,
      },
      {
        name: 'aminalIdOne',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'aminalIdTwo',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'childAminalId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'winningIds',
        internalType: 'uint256[8]',
        type: 'uint256[8]',
        indexed: false,
      },
    ],
    name: 'EndAuction',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'version', internalType: 'uint8', type: 'uint8', indexed: false },
    ],
    name: 'Initialized',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'previousOwner',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'newOwner',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
    ],
    name: 'OwnershipTransferred',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'auctionId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true,
      },
      {
        name: 'sender',
        internalType: 'address',
        type: 'address',
        indexed: false,
      },
      {
        name: 'visualId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'catEnum',
        internalType: 'enum VisualsAuction.VisualsCat',
        type: 'uint8',
        indexed: false,
      },
    ],
    name: 'ProposeVisual',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'auctionId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true,
      },
      {
        name: 'sender',
        internalType: 'address',
        type: 'address',
        indexed: false,
      },
      {
        name: 'visualId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'catEnum',
        internalType: 'enum VisualsAuction.VisualsCat',
        type: 'uint8',
        indexed: false,
      },
    ],
    name: 'RemoveVisual',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'auctionId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true,
      },
      {
        name: 'visualId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'sender',
        internalType: 'address',
        type: 'address',
        indexed: false,
      },
      {
        name: 'catEnum',
        internalType: 'enum VisualsAuction.VisualsCat',
        type: 'uint8',
        indexed: false,
      },
      {
        name: 'userLoveVote',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'totalLove',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'RemoveVisualVote',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'auctionId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true,
      },
      {
        name: 'aminalIdOne',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true,
      },
      {
        name: 'aminalIdTwo',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true,
      },
      {
        name: 'totalLove',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'visualIds',
        internalType: 'uint256[8][10]',
        type: 'uint256[8][10]',
        indexed: false,
      },
    ],
    name: 'StartAuction',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'auctionId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true,
      },
      {
        name: 'visualId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'sender',
        internalType: 'address',
        type: 'address',
        indexed: false,
      },
      {
        name: 'catEnum',
        internalType: 'enum VisualsAuction.VisualsCat',
        type: 'uint8',
        indexed: false,
      },
      {
        name: 'userLoveVote',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'totalLove',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'VisualsVote',
  },
  {
    type: 'function',
    inputs: [],
    name: 'GENERATOR_SOURCE_BALANCE',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'GENERATOR_SOURCE_CONTRACT',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'aminals',
    outputs: [{ name: '', internalType: 'contract Aminals', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'auctionCnt',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'auctionId', internalType: 'uint256', type: 'uint256' }],
    name: 'auctions',
    outputs: [
      { name: 'aminalIdOne', internalType: 'uint256', type: 'uint256' },
      { name: 'aminalIdTwo', internalType: 'uint256', type: 'uint256' },
      { name: 'totalLove', internalType: 'uint256', type: 'uint256' },
      { name: 'childAminalId', internalType: 'uint256', type: 'uint256' },
      { name: 'ended', internalType: 'bool', type: 'bool' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'auctionId', internalType: 'uint256', type: 'uint256' }],
    name: 'endAuction',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: 'auctionID', internalType: 'uint256', type: 'uint256' }],
    name: 'getAuctionByID',
    outputs: [
      {
        name: '',
        internalType: 'struct VisualsAuction.Auction',
        type: 'tuple',
        components: [
          { name: 'aminalIdOne', internalType: 'uint256', type: 'uint256' },
          { name: 'aminalIdTwo', internalType: 'uint256', type: 'uint256' },
          { name: 'totalLove', internalType: 'uint256', type: 'uint256' },
          {
            name: 'visualIds',
            internalType: 'uint256[8][10]',
            type: 'uint256[8][10]',
          },
          {
            name: 'visualIdVotes',
            internalType: 'uint256[8][10]',
            type: 'uint256[8][10]',
          },
          {
            name: 'visualNoVotes',
            internalType: 'uint256[8][10]',
            type: 'uint256[8][10]',
          },
          { name: 'childAminalId', internalType: 'uint256', type: 'uint256' },
          { name: 'winnerId', internalType: 'uint256[8]', type: 'uint256[8]' },
          { name: 'ended', internalType: 'bool', type: 'bool' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'owner',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'auctionId', internalType: 'uint256', type: 'uint256' },
      {
        name: 'catEnum',
        internalType: 'enum VisualsAuction.VisualsCat',
        type: 'uint8',
      },
      { name: 'visualId', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'proposeVisual',
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'auctionId', internalType: 'uint256', type: 'uint256' },
      {
        name: 'catEnum',
        internalType: 'enum VisualsAuction.VisualsCat',
        type: 'uint8',
      },
      { name: 'visualId', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'removeVisual',
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'renounceOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: '_aminals', internalType: 'address', type: 'address' }],
    name: 'setup',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'aminalIdOne', internalType: 'uint256', type: 'uint256' },
      { name: 'aminalIdTwo', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'startAuction',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: 'newOwner', internalType: 'address', type: 'address' }],
    name: 'transferOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'auctionId', internalType: 'uint256', type: 'uint256' },
      {
        name: 'catEnum',
        internalType: 'enum VisualsAuction.VisualsCat',
        type: 'uint8',
      },
      { name: 'visualId', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'voteVisual',
    outputs: [],
    stateMutability: 'payable',
  },
] as const

export const visualsAuctionAddress =
  '0x3350b16C29EA6EB7c0A0b40CB11Ba630eb511827' as const

export const visualsAuctionConfig = {
  address: visualsAuctionAddress,
  abi: visualsAuctionAbi,
} as const
